# SPDX-License-Identifier: Apache-2.0

global:
  nameOverride: Sub-Chart

#nifi:
#  enabled: true
#  image:
#    repository: https://github.com/frmscoe/helm/tree/main/nifi
#    tag: 1.0.0

arangodb:
  enabled: true
  image:
    repository: charts/arangodb-1.0.0.tgz
    tag: 2.0.0

arangodb-ingress:
  enabled: true
  image:
    repository: charts/arangodb-ingress-proxy-1.0.0.tgz
    tag: 1.0.0

apm:
  enabled: true
  image:
    repository: charts/apm-server-8.5.1.tgz
    tag: 1.0.0

logstash:
  enabled: true
  image:
    repository: charts/logstash-5.1.15.tgz
    tag: 1.0.0

jenkins:
  enabled: true
  image:
    repository: charts/jenkins-12.0.1.tgz
    tag: 1.0.0

keycloak:
  enabled: true
  image:
    repository: charts/keycloak-13.3.0.tgz
    tag: 1.0.0

elasticsearch:
  enabled: true
  image:
    repository: charts/elasticsearch-19.5.14.tgz
    tag: 1.0.0

nginx-ingress:
  enabled: true
  image:
    repository: charts/nginx-ingress-controller-9.3.32.tgz
    tag: 1.0.0

openfaas:
  enabled: true
  image:
    repository: charts/openfaas-12.0.2.tgz
    tag: 1.0.0

redis:
  enabled: true
  image:
    repository: charts/redis-17.8.5.tgz
    tag: 1.0.0

vault:
  enabled: true
  image:
    repository: charts/vault-0.23.0.tgz
    tag: 1.0.0
    
nuxeo:
  enabled: true
  image:
    repository: charts/nuxeo-1.0.0.tgz
    tag: 1.0.0

infra-chart:
  enabled: true
  image:
    repository: charts/infra-chart-1.0.0.tgz
    tag: 1.0.0
