# SPDX-License-Identifier: Apache-2.0

controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  admissionWebhooks:
    enabled: false
  service:
    type: ClusterIP
  tcp:
    configMapNamespace: default
  udp:
    configMapNamespace: default

tcp:
  9000: "default/test:8080"

udp:
  9001: "default/test:8080"
