# SPDX-License-Identifier: Apache-2.0

controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP

tcp:
  9000: "default/test:8080"
  9001: "default/test:8080"
