# SPDX-License-Identifier: Apache-2.0

controller:
  image:
    repository: ingress-controller/controller
    tag: 1.0.0-dev
    digest: null
  service:
    type: ClusterIP

podSecurityPolicy:
  enabled: true
