# SPDX-License-Identifier: Apache-2.0

# file: values.yaml
image:
  repository: arangodb/arangodb
  tag: latest
arangodb:
  storage:
    size: 100Gi
    class: gp2
  authentication:
    rootPassword: mysecretpassword
  serviceType: ClusterIP
  replicas: 1
  single:
    enabled: true
    imagePullPolicy: IfNotPresent
    image: arangodb/arangodb
    version: latest
    servicePort: 8529
