# SPDX-License-Identifier: Apache-2.0

{{- if ne .Values.mode "refresh" }}
apiVersion: v1
kind: Secret
metadata:
  name: frmpullsecret
  namespace: cicd
  labels:
{{ include "aws-ecr-credential.labels" . | indent 4 }}
type: Opaque
data:
  AWS_ECR_REGISTRY: {{ .Values.aws.ecrRegistry | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey | b64enc }}
{{- end }}
